spring:
  application:
    name: suggestion-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1q2w3e4r!
    url: jdbc:mysql://localhost:3306/suggestion_service_db?characterEncoding=UTF-8
  jpa:
    database: mysql
    hibernate:
      ddl-auto: create
    show-sql: true
  messages:
    basename: messages, errors

server:
  port: 0

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka